// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b14601af3fb2ad72d5048e94188a569a1838fb9c/clone/clone.d.ts
declare module "clone" {
    /**
     * @param val the value that you want to clone, any type allowed
     * @param circular Call clone with circular set to false if you are certain that obj contains no circular references. This will give better performance if needed. There is no error if undefined or null is passed as obj.
     * @param depth to wich the object is to be cloned (optional, defaults to infinity)
     */
    function clone<T>(val: T, circular?: boolean, depth?: number): T;

    namespace clone {
        /**
         * @param obj the object that you want to clone
         */
        function clonePrototype<T>(obj: T): T;
    }

    export = clone
}
