// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1da639a106527e0c4010b354a1efe52a3059a291/cors/cors.d.ts
declare module "cors" {
    import express = require('express');

    module e {
        interface CorsOptions  {
            origin?: any;
            methods?: any;
            allowedHeaders?: any;
            exposedHeaders?: any;
            credentials?: boolean;
            maxAge?: number;
        }
    }

    function e(options?: e.CorsOptions): express.RequestHandler;
    export = e;
}
