// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/fe563dff3428bac1260d1794e2c2ecf8f097535a/mockery/mockery.d.ts
declare module "mockery" {

    interface MockeryEnableArgs {
        useCleanCache?: boolean;
        warnOnReplace?: boolean;
        warnOnUnregistered?: boolean;
    }

    export function enable(args?: MockeryEnableArgs): void;
    export function disable(): void;

    export function registerMock(name: string, mock: any): void;
    export function deregisterMock(name: string): void;

    export function registerSubstitute(name: string, substitute: string): void;
    export function deregisterSubstitute(name: string): void;

    export function registerAllowable(name: string, unhook?: boolean): void;
    export function deregisterAllowable(name: string): void;

    export function registerAllowables(names: string[]): void;
    export function deregisterAllowables(names: string[]): void;

    export function deregisterAll(): void;
    export function resetCache(): void;
    export function warnOnUnregistered(value: boolean): void;
    export function warnOnReplace(value: boolean): void;
}
