// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1da639a106527e0c4010b354a1efe52a3059a291/debug/debug.d.ts
declare module "debug" {

    function d(namespace: string): d.Debugger;

    module d {
        export var log: Function;

        function enable(namespaces: string): void;
        function disable(): void;

        function enabled(namespace: string): boolean;

        export interface Debugger {
            (formatter: any, ...args: any[]): void;

            enabled:   boolean;
            log:       Function;
            namespace: string;
        }
    }

    export = d;

}
